reformat to adhere to autoformatters (#51)

diff --git a/bin/md-format b/bin/md-format
--- a/bin/md-format
+++ b/bin/md-format
@@ -14,47 +14,47 @@ set -Eeuo pipefail
 #
 
 init() {
-    VERBOSE="${VERBOSE:-false}"
-    THIS_SCRIPT="$(readlink -f "${0}")"
-    BIN_DIR="$(dirname "${THIS_SCRIPT}")"
-    REPO_DIR="$(dirname "${BIN_DIR}")"
-    PATH="${REPO_DIR}/node_modules/.bin:${PATH}"
+  VERBOSE="${VERBOSE:-false}"
+  THIS_SCRIPT="$(readlink -f "${0}")"
+  BIN_DIR="$(dirname "${THIS_SCRIPT}")"
+  REPO_DIR="$(dirname "${BIN_DIR}")"
+  PATH="${REPO_DIR}/node_modules/.bin:${PATH}"
 }
 
 log_verbose() {
-    test "${VERBOSE}" == "false" || echo "${*}"
+  test "${VERBOSE}" == "false" || echo "${*}"
 }
 
 format_file() {
-    log_verbose "formatting ${1}..."
-    remark --output "${1}" --frail "${1}"
+  log_verbose "formatting ${1}..."
+  remark --output "${1}" --frail "${1}"
 }
 
 markdown_files() {
-    find . -mindepth 1 -maxdepth 1 -type f -name '*.md'
-    find src -type f -name '*.md'
+  find . -mindepth 1 -maxdepth 1 -type f -name '*.md'
+  find src -type f -name '*.md'
 }
 
 ignore() {
-    grep --invert-match --fixed-strings "${1}"
+  grep --invert-match --fixed-strings "${1}"
 }
 
 main() {
-    init
-    local error_files=()
-    while read -r file; do
-        format_file "${file}" || error_files+=("${file}")
-    done < <(markdown_files | ignore contact.md)
-    if [ "${#error_files[@]}" -gt 0 ]; then
-        echo
-        echo "Files with warnings / errors:"
-        echo
-        for f in "${error_files[@]}"; do
-            echo "  ${f}"
-        done
-        echo
-        return 1
-    fi
+  init
+  local error_files=()
+  while read -r file; do
+    format_file "${file}" || error_files+=("${file}")
+  done < <(markdown_files | ignore contact.md)
+  if [ "${#error_files[@]}" -gt 0 ]; then
+    echo
+    echo "Files with warnings / errors:"
+    echo
+    for f in "${error_files[@]}"; do
+      echo "  ${f}"
+    done
+    echo
+    return 1
+  fi
 }
 
 main
